pipelines:
  - name: linkerd-deploy
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: alpine/k8s
            tag: v0.1.0
            autoPull: true
            registry: artifactory
            sourceRepository: linkerd-docker-local
    steps:
    - name: linkerdCheck
      type: Bash
      execution:
        onExecute:
          - linkerd version