resources:
  - name: petclinic_repo
    type: GitRepo
    configuration:
      path: mjmckay/workshop-jfrog-linkerd
      gitProvider: MyRepo
      branches:
        include: main
      buildOn:
        commit:                false
        pullRequestCreate:     false
        releaseCreate:  true

pipelines:
  - name: petclinic_deploy
    steps:
      - name: kubernetes_deploy
        type: Bash
        configuration:
          integrations:
            - name: MyCluster
          inputResources:
            - name: petclinic_repo
        execution:
          onExecute:
            - cd $res_gitRepo_resourcePath/spring-petclinic-cloud
            - export REPOSITORY_PREFIX=springcommunity
            - mkdir $HOME/.kube
            - echo $int_MyCluster_kubeconfig > $HOME/.kube/config
            - cat $HOME/.kube/config
            - kubectl apply -f k8s/init-namespace
            - kubectl apply -f k8s/init-services
            - helm repo add bitnami https://charts.bitnami.com/bitnami
            - helm repo update
            - helm install vets-db-mysql bitnami/mysql --namespace spring-petclinic --version 8.8.8 --set auth.database=service_instance_db
            - helm install visits-db-mysql bitnami/mysql --namespace spring-petclinic  --version 8.8.8 --set auth.database=service_instance_db
            - helm install customers-db-mysql bitnami/mysql --namespace spring-petclinic  --version 8.8.8 --set auth.database=service_instance_db
            - bash scripts/deployToKubernetes.sh
          onSuccess:
            - echo "Petclinic ${run_number} deployed!"
